### ISSUE TITLE
Raspberry pi

### ISSUE THREAD

**Issue by llemonS** [estevaofon/youtubebot#3]
tentei usar no raspberry pi mas não funfou, apareceu
no module named telegram.ext, e depois no module named urllib.request :(
teria como upar uma versão com as libs necessárias já incluidas?

**Comment by estevaofon** [comment]
Algo não deu certo na instalação dos módulos. Vou te falar como fazer de forma mais detalhada. Se aparecer algum erro me mostre da forma mais completa possível.
O ideal é que os projetos sejam rodados em ambientes virtuais isolados, por isso vamos utilizar o virtualenv.
Inicialmente instale o virtualenv, caso já não tenha instalado:
sudo pip install virtualenv
vá para o pasta do projeto do youtubebot e faça:
virtualenv -p python3 env
Ative o ambiente virtual:
source env/bin/activate
Instale as bibliotecas:
pip install -r requirements.txt
rode o bot:
python bot.py
